---
- name: Send webapp tarball
  become: true
  ansible.builtin.copy:
    src: webapp.tar.gz
    dest: /home/isucon/webapp.tar.gz

- name: Mkdir webapp
  become: true
  become_user: isucon
  ansible.builtin.file:
    path: /home/isucon/webapp
    state: directory

- name: Mkdir sql
  become: true
  become_user: isucon
  ansible.builtin.file:
    path: /home/isucon/webapp/sql
    state: directory

- name: Extract webapp.tar.gz into /home/isucon
  become: true
  become_user: isucon
  ansible.builtin.unarchive:
    remote_src: true
    src: /home/isucon/webapp.tar.gz
    dest: /home/isucon/

- name: Remove webapp.tar.gz
  become: true
  ansible.builtin.file:
    path: /home/isucon/webapp.tar.gz
    state: absent

- name: initilize database
  become: true
  shell: |
    mysql -uroot -e "
      DROP DATABASE IF EXISTS isupipe;
      CREATE DATABASE IF NOT EXISTS isupipe;
    "
- name: initialize tables
  become: true
  shell: |
    cat /home/isucon/webapp/sql/initdb.d/10_schema.sql | mysql -uisucon -pisucon

- name: Tasks for isupipe-go
  include_tasks: go.yaml

- name: Tasks for isupipe-node
  include_tasks: node.yaml

- name: Tasks for isupipe-perl
  include_tasks: perl.yaml

- name: Tasks for isupipe-php
  include_tasks: php.yaml

- name: Tasks for isupipe-python
  include_tasks: python.yaml

- name: Tasks for isupipe-ruby
  include_tasks: ruby.yaml

- name: Tasks for isupipe-rust
  include_tasks: rust.yaml