name: Go CI
on:
  push:
    branches: [main]
    paths:
      - bench/**/*
      - webapp/go/**/*
      - webapp/*.sh
      - webapp/*.sql
      - development/docker-compose-common.yml
      - development/docker-compose-go.yml
      - development/Makefile
      - .github/workflows/go.yml
  pull_request:
    paths:
      - bench/**/*
      - webapp/go/**/*
      - webapp/*.sh
      - webapp/*.sql
      - development/docker-compose-common.yml
      - development/docker-compose-go.yml
      - development/Makefile
      - .github/workflows/go.yml
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.21.1
    name: Build
    runs-on: [isucon13-ci]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      # to avoid error: Deleting the contents of '/home/ubuntu/actions-runner/_work/isucon13/isucon13'
      #                 Error: File was unable to be removed Error: EACCES: permission denied, rmdir
      - name: chown workdir
        run:
          sudo chown -R $USER:$USER /home/github/actions-runner/_work/isucon13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      # containers
      - name: "setup containers"
        working-directory: ./development
        run: |
          make down/go
          make up/go

      # bench
      - name: "[bench] Get deps"
        working-directory: ./bench
        env:
          TZ: Asia/Tokyo
        run: |
          go get -v -t -d ./...

      - name: "[bench] Test"
        working-directory: ./bench
        env:
          TZ: Asia/Tokyo
        run: |
          go clean -testcache
          go test -p=1 -v ./...

      - name: "run bench"
        working-directory: ./bench
        run: |
          make bench
